import { Game, InventoryItem } from './types';

// Date de business extrase din Excel (jocuri + inventar). Fără date personale.

export const SEED_GAMES: Omit<Game, 'id'>[] = [
  { name: "Cupluri celebre", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "Couple IQ", category: "Cuplu", instructions: "", favorite: false },
  { name: "Icebreaker - Licitatia", category: "Ice-breaker", instructions: "", favorite: false },
  { name: "Icebreaker", category: "Ice-breaker", instructions: "Tombola - biletele per categorii", favorite: false },
  { name: "Cutitul si furculita Classic", category: "Miri", instructions: "", favorite: false },
  { name: "Cutitul si furculita Tip Bingo", category: "Pe mese", instructions: "", favorite: false },
  { name: "Cutitul si furculita Friends Match", category: "Selecție invitați", instructions: "", favorite: false },
  { name: "Literele mirilor", category: "Pe mese", instructions: "", favorite: false },
  { name: "Scaunele arhaice", category: "Individual", instructions: "", favorite: false },
  { name: "Kahoot / Wedding IQ Battle", category: "Toți invitații", instructions: "", favorite: false },
  { name: "Scaunele muzicale (Varianta baby)", category: "Bully / Baby", instructions: "", favorite: false },
  { name: "Scavenger hunt", category: "Echipe / Fete vs Băieți", instructions: "bride & groom teams", favorite: false },
  { name: "Shazam", category: "Echipe / Fete vs Băieți", instructions: "Guess the first 5 seconds music playlist", favorite: false },
  { name: "Sing the lyrics", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "Masa meselor", category: "Pe mese", instructions: "", favorite: false },
  { name: "Pe aceesi unda", category: "1 vs 1", instructions: "", favorite: false },
  { name: "Teatru improvizat", category: "Echipe / Fete vs Băieți", instructions: "cum s-au cunoscut mirii, cererea in casatorie, o zi din casatoria lor: varianta ei/a lui", favorite: false },
  { name: "Find the guest - BINGO", category: "Toți invitații", instructions: "", favorite: false },
  { name: "Box and words", category: "Echipe / Fete vs Băieți", instructions: "cutiile de masina de spalat", favorite: false },
  { name: "Intrebari & Cantari", category: "Selecție invitați", instructions: "intrebari formate & titluri de cantari deja formate", favorite: false },
  { name: "Guess the popular couple", category: "Echipe / Fete vs Băieți", instructions: "images) - se afiseaza doar unul din cuplu", favorite: false },
  { name: "Guess the voice/ hand/ hair", category: "Selecție invitați", instructions: "", favorite: false },
  { name: "Bride & Groom Trivia Game (on paper)", category: "Pe mese", instructions: "", favorite: false },
  { name: "Ice-breaker: Find your match (cartonase cupluri celebre amestecate / cu pozele mirilor)", category: "Ice-breaker", instructions: "", favorite: false },
  { name: "Keyword speeches", category: "Speech / Keywords", instructions: "", favorite: false },
  { name: "Batalia Generatiilor", category: "Echipe", instructions: "", favorite: false },
  { name: "Cursa alinturilor", category: "Cuplu", instructions: "", favorite: false },
  { name: "Guess the food / drink", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "The Diaper Race", category: "Bully / Baby", instructions: "", favorite: false },
  { name: "Cursa in saci (clasic)", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "Noise Cancel War", category: "1 vs 1", instructions: "", favorite: false },
  { name: "Scaune si pahare muzicale", category: "Echipe / Fete vs Băieți", instructions: "pahare pe masa - la fiecare runda, pleaca 2-3 pahare) - se rotesc in jurul mesei", favorite: false },
  { name: "Daca in casa proprie (sceneta)", category: "Scenetă", instructions: "", favorite: false },
  { name: "Escape Room - The Stolen Rings", category: "Pe mese", instructions: "", favorite: false },
  { name: "Treasure Hunt", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "The objects race", category: "Echipe / Fete vs Băieți", instructions: "", favorite: false },
  { name: "The Wedding Heist", category: "Pe mese / Echipe", instructions: "cat mai multe obiecte dintr-o categorie per echipa/masa/ fete vs. baieti", favorite: false },
  { name: "UBER-ul imparatesc (reinterpretare Caleasca Imparateasca)", category: "Selecție invitați", instructions: "", favorite: false },
  { name: "How many objects", category: "Pe mese / Echipe", instructions: "", favorite: false },
  { name: "Telecomanda (sceneta)", category: "Selecție invitați", instructions: "", favorite: false },
  { name: "Chair Competition", category: "Selecție invitați", instructions: "Aruncatul papionului", favorite: false },
  { name: "Skanderberg Competition", category: "Selecție invitați", instructions: "Aruncatul buchetului", favorite: false },
  { name: "Wedding Gladiator Olympics", category: "1 vs 1", instructions: "10 mini-games battle", favorite: false },
  { name: "Big Brain Battle", category: "Echipe / Fete vs Băieți", instructions: "Despre Relatii, Istoria lumii, Muzica, Istoria mirilor, Geografia Romaniei, Autoturisme, Gastronomie, Moto (Te pui cu blondele", favorite: false },
  { name: "Wedding Brain Olympics", category: "Echipe / Fete vs Băieți", instructions: "10 mini-games battle", favorite: false },
  { name: "Labirintul Vocilor", category: "Cuplu", instructions: "Couples game - unul din cuplu este legat la ochi - participa aproximativ 10 cupluri, eu pun multe pahare, ei trebuie sa nu le calce, cu juriu pe fiecare. runde rapide de 3 vs 3. cine a castigat primeste premiu. fiecare cu culoarul lui.", favorite: false },
  { name: "Impossible Paper Plane / Love is in the Air", category: "1 vs 1", instructions: "cuplurile sunt legate la maini cu velcro (doar stanga cu dreapta) - li se arata cum se face un avion, primul cuplu care arunca avionul cel mai departe de linia de finish castiga.", favorite: false },
  { name: "The Challenge Wheel", category: "1 vs 1", instructions: "roata fizica, pe care am trecute provocarile - skanderberg, game of ken (spike), etc.", favorite: false },
  { name: "Golden Seat", category: "Ice-breaker", instructions: "cea mai simpla tombola - sub scaunul fiecaruia se afla un bilet auriu", favorite: false },
  { name: "Thug of war", category: "Pe mese / Echipe", instructions: "sfoara groasa (se echilibreaza - 10 barbati vs 20 fete, toti copiii vs 1/2 barbati", favorite: false },
  { name: "Guess the baby", category: "Pe mese / Echipe", instructions: "poze cu invitatii de cand erau bebelusi - echipele sa fie de la miri, mireasa combinate", favorite: false },
  { name: "The Emoji Game", category: "Selecție invitați", instructions: "necesita videoproiector) - buzz button - sau lingura - sau pliciul (primul plici pe masa", favorite: false },
  { name: "Ice-breaker \"The Survivor\": Toata lumea in picioare - dupa fiecare categorie, oamenii stau jos daca nu sunt in categorie - ramane 1 singur castigator", category: "Ice-breaker", instructions: "", favorite: false },
  { name: "Choose tie right line", category: "Selecție invitați", instructions: "intrebarile de la pantofii - dar toti prietenii se aseaza in spatele mirelui sau a miresei - ca forma de raspuns", favorite: false },
  { name: "Shakespeare competition", category: "Pe mese / Echipe", instructions: "fiecare masa primeste un set de keywords - extra puncte daca il canta", favorite: false },
  { name: "The Mistery Box", category: "Echipe / Fete vs Băieți", instructions: "o cutie pentru fiecare echipa cu aceleasi 10 alimente/bauturi infoliate in stalion - cine termina primul sacul castiga", favorite: false },
  { name: "Water Ping", category: "Echipe / Fete vs Băieți", instructions: "Pong (Clasic Beer Ping-Pong) - Pahare in piramida cu apa in ele (doua mese lungi de la bise) + ping-pong balls", favorite: false },
  { name: "Keyword Karaoke", category: "Echipe / Fete vs Băieți", instructions: "primesti un cuvant - primul care vine cu o melodie si fredoneaza melodia avand keyword in cantec castiga", favorite: false },
  { name: "Step the step", category: "Selecție invitați", instructions: "se creeaza mai multe chenare cu scoci colorat pe podea) - timp de 1 minut, trebuie sa sara in acel chenar pana la final - la final cine ramane in chenar castiga", favorite: false },
  { name: "Rings race", category: "Echipe / Fete vs Băieți", instructions: "exista 2 randuri - o sfoara la fiecare de 50 de metri prin care treci inelul - prin majoritatea invitatilor - cine ajunge primul la final castiga", favorite: false },
  { name: "Wedding Alias", category: "Selecție invitați", instructions: "3 persoane din fiecare echipa - cate cuvinte pot face in 90 de secunde - cele doua persoane vad cuvantul - apoi pe rand vor forma o propozitie, spunand cate un cuvant pe rand - a 3-a persoana este cea care ghiceste", favorite: false },
  { name: "Cups Holder", category: "Necategorisit", instructions: "mirele si mireasa sau reprezentantii mirilor - stau intr-o pozitie pe scaun - si invitatii vor pune cat mai multe pahare pe ei fara sa cada", favorite: false },
  { name: "Ice breaker", category: "Ice-breaker", instructions: "Win, Drink and Clean", favorite: false },
  { name: "Fastest Baby Meal", category: "Selecție invitați", instructions: "", favorite: false },
  { name: "Masa Meselor 2", category: "Necategorisit", instructions: "obiecte random (care nu sunt de la masa lor", favorite: false },
  { name: "Domino", category: "Necategorisit", instructions: "", favorite: false },
  { name: "Classic Trivia", category: "Necategorisit", instructions: "10 categorii din care mirii sunt implicati - fiecare are 3 nivele de greutate - videoproiector si laptop", favorite: false },
  { name: "The Bible Present", category: "Necategorisit", instructions: "o masa, o biblie si markere - fiecare invitat poate sa marcheze cu markerul versete pe care sa le lase amintire mirilor", favorite: false },
  { name: "Crossword", category: "Interactive Canvas", instructions: "giante canvas + sevalet) - cu cuvintele din povestea mirilor", favorite: false },
  { name: "Find the word", category: "Interactive Canvas", instructions: "selectie de 100 de cuvinte, puse pe un canvas urias - cu marker, trebuie sa incercuiasca cuvantul gasit, si sa taie cuvantul gasit din lista", favorite: false },
  { name: "Marriage Mad Libs", category: "Interactive Canvas", instructions: "campuri libere de completat", favorite: false },
  { name: "The Sticker Puzzle", category: "Interactive Canvas", instructions: "fiecare invitat are sub scaun / sub farfurie un sticker - tip piesa puzzle pe carei l duce pe o tabla unde formeaza un tabloou cu mirii", favorite: false },
  { name: "Doodle yourself", category: "Interactive Canvas", instructions: "", favorite: false },
];

export const SEED_INVENTORY: Omit<InventoryItem, 'id'>[] = [
  { name: "Turnball", qty: 1, notes: '' },
  { name: "Tinta + arc + 2 sageti", qty: 2, notes: '' },
  { name: "Giant Jenga", qty: 2, notes: '' },
  { name: "CornHole", qty: 2, notes: '' },
  { name: "Tic-Tac-Toe", qty: 3, notes: '' },
  { name: "Badminton + Fileu", qty: 1, notes: '' },
  { name: "Tin Can Toss", qty: 2, notes: '' },
];

export const GAME_CATEGORIES: string[] = [
  "1 vs 1",
  "Bully / Baby",
  "Cuplu",
  "Echipe",
  "Echipe / Fete vs Băieți",
  "Ice-breaker",
  "Individual",
  "Interactive Canvas",
  "Miri",
  "Necategorisit",
  "Pe mese",
  "Pe mese / Echipe",
  "Scenetă",
  "Selecție invitați",
  "Speech / Keywords",
  "Toți invitații",
];
