-- EMZEE seed: jocuri + inventar (business, fără date personale).
-- Rulează după schema.sql.

insert into games (name, category, instructions) values ('Cupluri celebre', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('Couple IQ', 'Cuplu', '');
insert into games (name, category, instructions) values ('Icebreaker - Licitatia', 'Ice-breaker', '');
insert into games (name, category, instructions) values ('Icebreaker', 'Ice-breaker', 'Tombola - biletele per categorii');
insert into games (name, category, instructions) values ('Cutitul si furculita Classic', 'Miri', '');
insert into games (name, category, instructions) values ('Cutitul si furculita Tip Bingo', 'Pe mese', '');
insert into games (name, category, instructions) values ('Cutitul si furculita Friends Match', 'Selecție invitați', '');
insert into games (name, category, instructions) values ('Literele mirilor', 'Pe mese', '');
insert into games (name, category, instructions) values ('Scaunele arhaice', 'Individual', '');
insert into games (name, category, instructions) values ('Kahoot / Wedding IQ Battle', 'Toți invitații', '');
insert into games (name, category, instructions) values ('Scaunele muzicale (Varianta baby)', 'Bully / Baby', '');
insert into games (name, category, instructions) values ('Scavenger hunt', 'Echipe / Fete vs Băieți', 'bride & groom teams');
insert into games (name, category, instructions) values ('Shazam', 'Echipe / Fete vs Băieți', 'Guess the first 5 seconds music playlist');
insert into games (name, category, instructions) values ('Sing the lyrics', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('Masa meselor', 'Pe mese', '');
insert into games (name, category, instructions) values ('Pe aceesi unda', '1 vs 1', '');
insert into games (name, category, instructions) values ('Teatru improvizat', 'Echipe / Fete vs Băieți', 'cum s-au cunoscut mirii, cererea in casatorie, o zi din casatoria lor: varianta ei/a lui');
insert into games (name, category, instructions) values ('Find the guest - BINGO', 'Toți invitații', '');
insert into games (name, category, instructions) values ('Box and words', 'Echipe / Fete vs Băieți', 'cutiile de masina de spalat');
insert into games (name, category, instructions) values ('Intrebari & Cantari', 'Selecție invitați', 'intrebari formate & titluri de cantari deja formate');
insert into games (name, category, instructions) values ('Guess the popular couple', 'Echipe / Fete vs Băieți', 'images) - se afiseaza doar unul din cuplu');
insert into games (name, category, instructions) values ('Guess the voice/ hand/ hair', 'Selecție invitați', '');
insert into games (name, category, instructions) values ('Bride & Groom Trivia Game (on paper)', 'Pe mese', '');
insert into games (name, category, instructions) values ('Ice-breaker: Find your match (cartonase cupluri celebre amestecate / cu pozele mirilor)', 'Ice-breaker', '');
insert into games (name, category, instructions) values ('Keyword speeches', 'Speech / Keywords', '');
insert into games (name, category, instructions) values ('Batalia Generatiilor', 'Echipe', '');
insert into games (name, category, instructions) values ('Cursa alinturilor', 'Cuplu', '');
insert into games (name, category, instructions) values ('Guess the food / drink', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('The Diaper Race', 'Bully / Baby', '');
insert into games (name, category, instructions) values ('Cursa in saci (clasic)', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('Noise Cancel War', '1 vs 1', '');
insert into games (name, category, instructions) values ('Scaune si pahare muzicale', 'Echipe / Fete vs Băieți', 'pahare pe masa - la fiecare runda, pleaca 2-3 pahare) - se rotesc in jurul mesei');
insert into games (name, category, instructions) values ('Daca in casa proprie (sceneta)', 'Scenetă', '');
insert into games (name, category, instructions) values ('Escape Room - The Stolen Rings', 'Pe mese', '');
insert into games (name, category, instructions) values ('Treasure Hunt', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('The objects race', 'Echipe / Fete vs Băieți', '');
insert into games (name, category, instructions) values ('The Wedding Heist', 'Pe mese / Echipe', 'cat mai multe obiecte dintr-o categorie per echipa/masa/ fete vs. baieti');
insert into games (name, category, instructions) values ('UBER-ul imparatesc (reinterpretare Caleasca Imparateasca)', 'Selecție invitați', '');
insert into games (name, category, instructions) values ('How many objects', 'Pe mese / Echipe', '');
insert into games (name, category, instructions) values ('Telecomanda (sceneta)', 'Selecție invitați', '');
insert into games (name, category, instructions) values ('Chair Competition', 'Selecție invitați', 'Aruncatul papionului');
insert into games (name, category, instructions) values ('Skanderberg Competition', 'Selecție invitați', 'Aruncatul buchetului');
insert into games (name, category, instructions) values ('Wedding Gladiator Olympics', '1 vs 1', '10 mini-games battle');
insert into games (name, category, instructions) values ('Big Brain Battle', 'Echipe / Fete vs Băieți', 'Despre Relatii, Istoria lumii, Muzica, Istoria mirilor, Geografia Romaniei, Autoturisme, Gastronomie, Moto (Te pui cu blondele');
insert into games (name, category, instructions) values ('Wedding Brain Olympics', 'Echipe / Fete vs Băieți', '10 mini-games battle');
insert into games (name, category, instructions) values ('Labirintul Vocilor', 'Cuplu', 'Couples game - unul din cuplu este legat la ochi - participa aproximativ 10 cupluri, eu pun multe pahare, ei trebuie sa nu le calce, cu juriu pe fiecare. runde rapide de 3 vs 3. cine a castigat primeste premiu. fiecare cu culoarul lui.');
insert into games (name, category, instructions) values ('Impossible Paper Plane / Love is in the Air', '1 vs 1', 'cuplurile sunt legate la maini cu velcro (doar stanga cu dreapta) - li se arata cum se face un avion, primul cuplu care arunca avionul cel mai departe de linia de finish castiga.');
insert into games (name, category, instructions) values ('The Challenge Wheel', '1 vs 1', 'roata fizica, pe care am trecute provocarile - skanderberg, game of ken (spike), etc.');
insert into games (name, category, instructions) values ('Golden Seat', 'Ice-breaker', 'cea mai simpla tombola - sub scaunul fiecaruia se afla un bilet auriu');
insert into games (name, category, instructions) values ('Thug of war', 'Pe mese / Echipe', 'sfoara groasa (se echilibreaza - 10 barbati vs 20 fete, toti copiii vs 1/2 barbati');
insert into games (name, category, instructions) values ('Guess the baby', 'Pe mese / Echipe', 'poze cu invitatii de cand erau bebelusi - echipele sa fie de la miri, mireasa combinate');
insert into games (name, category, instructions) values ('The Emoji Game', 'Selecție invitați', 'necesita videoproiector) - buzz button - sau lingura - sau pliciul (primul plici pe masa');
insert into games (name, category, instructions) values ('Ice-breaker "The Survivor": Toata lumea in picioare - dupa fiecare categorie, oamenii stau jos daca nu sunt in categorie - ramane 1 singur castigator', 'Ice-breaker', '');
insert into games (name, category, instructions) values ('Choose tie right line', 'Selecție invitați', 'intrebarile de la pantofii - dar toti prietenii se aseaza in spatele mirelui sau a miresei - ca forma de raspuns');
insert into games (name, category, instructions) values ('Shakespeare competition', 'Pe mese / Echipe', 'fiecare masa primeste un set de keywords - extra puncte daca il canta');
insert into games (name, category, instructions) values ('The Mistery Box', 'Echipe / Fete vs Băieți', 'o cutie pentru fiecare echipa cu aceleasi 10 alimente/bauturi infoliate in stalion - cine termina primul sacul castiga');
insert into games (name, category, instructions) values ('Water Ping', 'Echipe / Fete vs Băieți', 'Pong (Clasic Beer Ping-Pong) - Pahare in piramida cu apa in ele (doua mese lungi de la bise) + ping-pong balls');
insert into games (name, category, instructions) values ('Keyword Karaoke', 'Echipe / Fete vs Băieți', 'primesti un cuvant - primul care vine cu o melodie si fredoneaza melodia avand keyword in cantec castiga');
insert into games (name, category, instructions) values ('Step the step', 'Selecție invitați', 'se creeaza mai multe chenare cu scoci colorat pe podea) - timp de 1 minut, trebuie sa sara in acel chenar pana la final - la final cine ramane in chenar castiga');
insert into games (name, category, instructions) values ('Rings race', 'Echipe / Fete vs Băieți', 'exista 2 randuri - o sfoara la fiecare de 50 de metri prin care treci inelul - prin majoritatea invitatilor - cine ajunge primul la final castiga');
insert into games (name, category, instructions) values ('Wedding Alias', 'Selecție invitați', '3 persoane din fiecare echipa - cate cuvinte pot face in 90 de secunde - cele doua persoane vad cuvantul - apoi pe rand vor forma o propozitie, spunand cate un cuvant pe rand - a 3-a persoana este cea care ghiceste');
insert into games (name, category, instructions) values ('Cups Holder', 'Necategorisit', 'mirele si mireasa sau reprezentantii mirilor - stau intr-o pozitie pe scaun - si invitatii vor pune cat mai multe pahare pe ei fara sa cada');
insert into games (name, category, instructions) values ('Ice breaker', 'Ice-breaker', 'Win, Drink and Clean');
insert into games (name, category, instructions) values ('Fastest Baby Meal', 'Selecție invitați', '');
insert into games (name, category, instructions) values ('Masa Meselor 2', 'Necategorisit', 'obiecte random (care nu sunt de la masa lor');
insert into games (name, category, instructions) values ('Domino', 'Necategorisit', '');
insert into games (name, category, instructions) values ('Classic Trivia', 'Necategorisit', '10 categorii din care mirii sunt implicati - fiecare are 3 nivele de greutate - videoproiector si laptop');
insert into games (name, category, instructions) values ('The Bible Present', 'Necategorisit', 'o masa, o biblie si markere - fiecare invitat poate sa marcheze cu markerul versete pe care sa le lase amintire mirilor');
insert into games (name, category, instructions) values ('Crossword', 'Interactive Canvas', 'giante canvas + sevalet) - cu cuvintele din povestea mirilor');
insert into games (name, category, instructions) values ('Find the word', 'Interactive Canvas', 'selectie de 100 de cuvinte, puse pe un canvas urias - cu marker, trebuie sa incercuiasca cuvantul gasit, si sa taie cuvantul gasit din lista');
insert into games (name, category, instructions) values ('Marriage Mad Libs', 'Interactive Canvas', 'campuri libere de completat');
insert into games (name, category, instructions) values ('The Sticker Puzzle', 'Interactive Canvas', 'fiecare invitat are sub scaun / sub farfurie un sticker - tip piesa puzzle pe carei l duce pe o tabla unde formeaza un tabloou cu mirii');
insert into games (name, category, instructions) values ('Doodle yourself', 'Interactive Canvas', '');

insert into inventory (name, qty) values ('Turnball', 1);
insert into inventory (name, qty) values ('Tinta + arc + 2 sageti', 2);
insert into inventory (name, qty) values ('Giant Jenga', 2);
insert into inventory (name, qty) values ('CornHole', 2);
insert into inventory (name, qty) values ('Tic-Tac-Toe', 3);
insert into inventory (name, qty) values ('Badminton + Fileu', 1);
insert into inventory (name, qty) values ('Tin Can Toss', 2);